export const Projects = [
    {   
        id: 1,
        title: 'Project 1',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 2,
        title: 'Project 2',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 3,
        title: 'Project 3',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 4,
        title: 'Project 4',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 5,
        title: 'Project 5',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 6,
        title: 'Project 6',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 7,
        title: 'Project 7',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
    {   
        id: 8,
        title: 'Project 8',
        drescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        position: ['Front-end'],
        category: ['Web Application'],
        tools: ['React', 'Typescript', 'Tailwind', 'DaisyUI'],
        create_at: '2025/04/24',
        update_at: '2025/04/24',
    },
]